# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: "Arch Linux's printsrcinfo action"
description: "GitHub Action to generate .SRCINFO for a given PKGBUILD"
author: 'mkopec'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  path:
    description: 'Location for this action to run'
    default: ''
    required: false

runs:
  using: 'docker'
  image: 'docker://ghcr.io/mkopec/archlinux-package-action:2'
  args:
    - ${{ inputs.path }}
