name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - "main"

jobs:
  publish:
    name: Publish OCI image
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: OCI metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=edge,branch=main
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          containerfiles: |
            ./Dockerfile
          extra-args: |
            --pull

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io
          extra-args: |
            --disable-content-trust

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: publish
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get branch/tag names
        id: branch-name
        uses: tj-actions/branch-names@v7
        with:
          strip_tag_prefix: "v"

      - name: Read changelog
        id: changelog-reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.branch-name.outputs.tag }}
          path: ./CHANGELOG.md

      - name: Create/update release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.branch-name.outputs.tag }}
          name: v${{ steps.branch-name.outputs.tag }}
          body: ${{ steps.changelog-reader.outputs.changes }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
